name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: build
        run: make
        working-directory: build/linux-qvm

  update-latest:
    needs: [build] 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - artifact_dir: build/linux-qvm
            artifact_name: zz-osp-pak8.pk3

              #    steps:
              #
              #      - uses: actions/checkout@v4
              #        
              #      - name: Upload archive
              #        working-directory: .
              #        uses: "svenstaro/upload-release-action@latest"
              #        with:
              #          automatic_release_tag: Latest
              #          repo_token: ${{ secrets.GITHUB_TOKEN }}
              #          tag: ${{ github.ref }}
              #          overwrite: true
              #          file: build/linux-qvm/zz-osp-pak8.pk3
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Upload archive
        uses: "svenstaro/upload-release-action@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file: ./${{ matrix.artifact_dir }}/${{ matrix.artifact_name }}

