name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-qvm:
   #name: ${{ matrix.btype }} Ubuntu ${{ matrix.arch }}
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: build
      working-directory: build/linux-qvm
      run: | 
        make

    - uses: actions/upload-artifact@v4
      #if: matrix.cc == 'gcc' && matrix.btype == 'release'
      with:
        name: zz-osp-pak8.pk3
        path: build/linux-qvm/zz-osp-pak8.pk3
        if-no-files-found: error
        retention-days: 5

  create-latest:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [linux-qvm]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create latest build
        uses: czietz/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          overwrite: true
          title: Latest Build
          files: |
            zz-osp-pak8.pk3

            #  update-release:
            #    if: ${{ github.event_name == 'release' }}
            #    needs: [linux-qvm]
            #    runs-on: ubuntu-latest
            #
            #    steps:
            #      - name: Download Artifacts
            #        uses: actions/download-artifact@v4
            #
            #      - name: Upload archive
            #        uses: "svenstaro/upload-release-action@latest"
            #        with:
            #          repo_token: ${{ secrets.GITHUB_TOKEN }}
            #          tag: ${{ github.ref }}
            #          overwrite: true
            #          file: zz-osp-pak8.pk3


