name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
  
      - name: build
        run: make
        working-directory: ./build/linux-qvm

      - name: Upload archive
        uses: "svenstaro/upload-release-action@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file: ./build/linux-qvm/zz-osp-pak8.pk3
