name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: make
      working-directory: ./build/linux-qvm
      
    - name: Create latest build
      uses: "svenstaro/upload-release-action@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        overwrite: true
        file: ${{ matrix.artifact_name }}
